"""Head-to-head against SQLite on identical generated data.

Tests the Part-2 claim that SQLite's R*Tree gives an indexed interval-overlap
path that Ladybug structurally cannot offer on relationship properties.
"""
import os as _os, pathlib as _pl, sys as _sys
_HERE = _pl.Path(__file__).resolve().parent
WORK = _os.environ.get("ORRERY_WORK", str(_HERE / "_work"))
_os.makedirs(WORK, exist_ok=True)
_sys.path.insert(0, str(_HERE))

import sqlite3, csv, time, os, statistics, sys

SCALE = sys.argv[1] if len(sys.argv) > 1 else "L"
D = f"{WORK}/data_{SCALE}"
DB = f"{WORK}/orrery_{SCALE}.sqlite"
os.path.exists(DB) and os.remove(DB)

if not _os.path.isdir(D):
    _sys.exit(f"PREREQUISITE MISSING: {D}\n"
              f"This script loads CSVs generated by orrery_spike.py.\n"
              f"Run first:  python3 evidence/orrery_spike.py {SCALE}   "
              f"(L takes ~2 min)")
con = sqlite3.connect(DB)
con.execute("PRAGMA journal_mode=WAL")
con.executescript("""
CREATE TABLE person(id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE event(id INTEGER PRIMARY KEY, name TEXT, start_ts INT, end_ts INT, kind TEXT);
CREATE TABLE room(id INTEGER PRIMARY KEY, name TEXT, capacity INT);
CREATE TABLE attends(person_id INT, event_id INT, start_ts INT, end_ts INT,
                     priority_person REAL, priority_coord REAL, coord_binding INT,
                     source TEXT, pinned INT);
CREATE TABLE held(room_id INT, event_id INT, start_ts INT, end_ts INT,
                  posture TEXT, overflow_for INT, capacity_override INT);
""")

def load(table, fn, ncols):
    with open(f"{D}/{fn}") as f:
        rows = [r[:ncols] for r in csv.reader(f)]
    con.executemany(f"INSERT INTO {table} VALUES({','.join('?'*ncols)})", rows)
    return len(rows)

t0 = time.perf_counter()
load("person", "person.csv", 2)
load("event", "event.csv", 5)
load("room", "room.csv", 3)
n_att = load("attends", "attends.csv", 9)
load("held", "held.csv", 7)

# conventional b-tree indices
# Phase-0 correction (2026-08-01, phases/00-grounding.md): ix_att_e restored.
# The handoff shipped without it — the "fair idx" configuration RESEARCH-0003
# publishes (Q7b 1.2 ms) requires it; without it Q7b degenerates to a scan
# plan (measured 2,638 ms at L; 0.46 ms once indexed, same result count).
con.executescript("""
CREATE INDEX ix_att_p ON attends(person_id, start_ts, end_ts);
CREATE INDEX ix_att_e ON attends(event_id, person_id);
CREATE INDEX ix_held_r ON held(room_id, start_ts, end_ts);
""")

# R*Tree: 1-D interval index over attends, keyed by rowid
con.executescript("""
CREATE VIRTUAL TABLE attends_rt USING rtree(id, lo, hi);
INSERT INTO attends_rt SELECT rowid, start_ts, end_ts FROM attends;
""")
con.commit()
load_s = time.perf_counter() - t0
size = os.path.getsize(DB) / 1e6
print(f"SQLite load: {load_s:.1f}s   on-disk: {size:.0f} MB   ({n_att:,} attends rows)\n")

def bench(label, sql, params=(), n=3):
    out = None
    ts = []
    for _ in range(n):
        t = time.perf_counter()
        out = con.execute(sql, params).fetchall()
        ts.append((time.perf_counter() - t) * 1000)
    r = out[0][0] if out and out[0] else "-"
    print(f"{label:44s} {statistics.median(ts):9.1f}ms   {r}")
    return statistics.median(ts)

PID = 7
print(f"{'query':44s} {'median':>11s}   result")
print("-" * 72)

bench("Q2 conflict detect (per-person, b-tree)", """
SELECT count(*) FROM attends a1 JOIN attends a2
  ON a1.person_id=a2.person_id AND a1.event_id < a2.event_id
WHERE a1.person_id=? AND a1.start_ts < a2.end_ts AND a2.start_ts < a1.end_ts""", (PID,))

bench("Q3 conflict sweep (GLOBAL, b-tree)", """
SELECT count(*) FROM attends a1 JOIN attends a2
  ON a1.person_id=a2.person_id AND a1.event_id < a2.event_id
WHERE a1.start_ts < a2.end_ts AND a2.start_ts < a1.end_ts""")

bench("Q3 conflict sweep (GLOBAL, R*Tree)", """
SELECT count(*) FROM attends a1
JOIN attends_rt rt ON rt.lo < a1.end_ts AND rt.hi > a1.start_ts
JOIN attends a2 ON a2.rowid = rt.id
WHERE a2.person_id = a1.person_id AND a1.event_id < a2.event_id""")

bench("Q5 room exclusivity (GLOBAL)", """
SELECT count(*) FROM held h1 JOIN held h2
  ON h1.room_id=h2.room_id AND h1.event_id < h2.event_id
WHERE h1.start_ts < h2.end_ts AND h2.start_ts < h1.end_ts
  AND h2.overflow_for <> h1.room_id""")

bench("Q7b co-attend 2-hop (windowed)", """
SELECT count(DISTINCT a2.person_id) FROM attends a1
JOIN event e ON e.id=a1.event_id
JOIN attends a2 ON a2.event_id=a1.event_id
WHERE a1.person_id=? AND e.start_ts BETWEEN 300000 AND 600000""", (PID,))

# recursive CTE equivalent of the group-hierarchy expansion (Q1)
con.executescript("""
CREATE TABLE grp(id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE member_of(person_id INT, grp_id INT, valid_from INT, valid_to INT, role TEXT);
CREATE TABLE subgroup_of(child INT, parent INT, valid_from INT, valid_to INT);
CREATE TABLE expects(grp_id INT, event_id INT, obligation TEXT, default_priority REAL,
                     valid_from INT, valid_to INT, cascades TEXT);
""")
load("grp", "group.csv", 2); load("member_of", "member_of.csv", 5)
load("subgroup_of", "subgroup_of.csv", 4); load("expects", "expects.csv", 7)
con.executescript("""
CREATE INDEX ix_mem ON member_of(person_id);
CREATE INDEX ix_sub ON subgroup_of(child);
CREATE INDEX ix_exp ON expects(grp_id);
""")
con.commit()

bench("Q1 derived expansion (recursive CTE)", """
WITH RECURSIVE reach(gid, depth) AS (
  SELECT grp_id, 0 FROM member_of
   WHERE person_id=? AND valid_from<=? AND valid_to>=?
  UNION
  SELECT s.parent, r.depth+1 FROM subgroup_of s JOIN reach r ON s.child=r.gid
   WHERE r.depth < 5 AND s.valid_from<=? AND s.valid_to>=?
)
SELECT count(DISTINCT x.event_id) FROM expects x JOIN reach r ON x.grp_id=r.gid
 WHERE x.valid_from<=? AND x.valid_to>=?""", (PID, 604800, 604800, 604800, 604800, 604800, 604800))
con.close()
